name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write
      checks: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2.12.0
      with:
        gradle-version: wrapper
        arguments: check
    - name: Publish Test Report
      if: success() || failure()
      uses: scacap/action-surefire-report@v1
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'


  dependabot-merge:
    needs: build
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@v1
      id: findpr
      with:
        github-token: ${{ github.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: merge-if-built
      uses: fastify/github-action-merge-dependabot@v3
      continue-on-error: true
      with:
        pr-number: ${{ steps.findpr.outputs.pr }}
        target: minor
        merge-method: rebase
